from dataclasses import dataclass
from typing import BinaryIO, Iterable, Optional, Protocol, Tuple, List, Set

@dataclass
class StorageRef:
    provider: str
    root_id: str
    key: str

@dataclass
class StorageItem:
    ref: StorageRef
    name: str
    is_dir: bool
    size_bytes: int
    modified_utc: float
    etag: Optional[str] = None
    mime_type: Optional[str] = None

class StorageProvider(Protocol):
    # Identity
    def provider_name(self) -> str: ...
    def root_id(self) -> str: ...
    
    # Path helpers
    def join(self, *parts: str) -> str: ...
    def ref(self, key: str) -> StorageRef: ...

    # Existence & listing
    def exists(self, ref: StorageRef) -> bool: ...
    def stat(self, ref: StorageRef) -> StorageItem: ...
    def listdir(self, ref: StorageRef) -> Iterable[StorageItem]: ...
    def walk(self, ref: StorageRef, extensions: Optional[Set[str]] = None) -> Iterable[StorageItem]: ...

    # IO
    def open_read(self, ref: StorageRef) -> BinaryIO: ...
    def open_write(self, ref: StorageRef, overwrite: bool = True) -> BinaryIO: ...
    def put_bytes(self, ref: StorageRef, data: bytes, overwrite: bool = True) -> None: ...
    def get_bytes(self, ref: StorageRef, max_bytes: Optional[int] = None) -> bytes: ...

    # File operations
    def mkdirs(self, ref: StorageRef) -> None: ...
    def delete(self, ref: StorageRef) -> None: ...
    def copy(self, src: StorageRef, dst: StorageRef, overwrite: bool = False) -> None: ...
    def move(self, src: StorageRef, dst: StorageRef, overwrite: bool = False) -> None: ...

    # Local access
    def to_local_path(self, ref: StorageRef) -> Optional[str]: ...
    def ensure_local_cache(self, ref: StorageRef) -> str: ...

    # Changes (stubs)
    def get_change_token(self) -> Optional[str]: ...
    def poll_changes(self, since_token: Optional[str]) -> Tuple[List[StorageItem], Optional[str]]: ...
