apiVersion: v1
kind: Service
metadata:
  name: ai-asset-memory-service
spec:
  selector:
    app: ai-asset-memory-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 17831
  type: LoadBalancer
